services:
  replicate-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8057:8000"
    environment:
      - DENO_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:8000/v1/models').then(r => r.ok ? Deno.exit(0) : Deno.exit(1))"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - claude-network
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  claude-network:
    driver: bridge